version: '3.5'

services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  tensorflow-jupyter:
    platform: linux/arm64/v8
    build: images_api
    volumes:
      - ./src:/tf
    ports:
      - "8888:8888"
