version: '3.5'

services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  tensorflow-jupyter:
    image: tensorflow/tensorflow:nightly-jupyter
    volumes:
      - ./src:/tf
    ports:
      - "8888:8888"
