version: '3.5'

services:
  images_api:
    build: images_api
    volumes:
      - ./images_api/src:/app
    environment:
      QDRANT_HOST: qdrant
      QDRANT_COLLECTION_NAME: images_collection

    ports:
      - 80:80
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

#  tensorflow-jupyter:
#    platform: linux/arm64/v8
#    build: images_api
#    volumes:
#      - ./src:/tf
#    ports:
#      - "8888:8888"
